minor debug

diff --git a/vpl_execution b/vpl_execution
--- a/vpl_execution
+++ b/vpl_execution
@@ -77,11 +77,11 @@ if [ -n "$DOCKER" ] ; then
     DOCKERHOSTNAME="pouet"
     DOCKEROPT="$DOCKEROPT -d --rm -w $RUNDIR --hostname $DOCKERHOSTNAME" # detached, auto-remove
     DOCKERID=$(docker run $DOCKEROPT $DOCKER sleep $DOCKERTIMEOUT)
-    echo "Run Docker $DOCKER."
+    echo "Run Docker $DOCKER ($DOCKERID)."
 
     # copy all RUNDIR inside docker...
     docker cp $RUNDIR/. $DOCKERID:$RUNDIR &> /dev/null
-    [ $? -ne 0 ] && echo "⚠ Warning: fails to copy \"$RUNDIR\" into docker!" && exit 0
+    [ $? -ne 0 ] && echo "⚠ Warning: fails to copy \"$RUNDIR\" into docker!" # && exit 0
 
     # chown RUNDIR as docker user
     if [ -n "$DOCKERUSER" ] ; then
