minor bug fix

diff --git a/vpl_execution b/vpl_execution
--- a/vpl_execution
+++ b/vpl_execution
@@ -6,16 +6,16 @@ if [ -f ./env.sh ] ; then
     elif [ -f $HOME/env.sh ] ; then
     source $HOME/env.sh
 else
-    echo "⚠ File \"env.sh\" is missing!" && exit 0
+    echo "⚠ Error: File \"env.sh\" is missing!" && exit 0
 fi
 
-[ -z "$MODE" ] && echo "⚠ Variable \"MODE\" is not defined!" && exit 0
+[ -z "$MODE" ] && echo "⚠ Error: Variable \"MODE\" is not defined!" && exit 0
 grep -w $MODE <<< "RUN DEBUG EVAL" &> /dev/null
-[ $? -ne 0 ] && echo "⚠ Invalid MODE \"$MODE\"!" && exit 0
-[ -z "$RUNDIR" ] && echo "⚠ Variable \"RUNDIR\" is not defined!" && exit 0
-[ -z "$ENTRYPOINT" ] && echo "⚠ Variable \"ENTRYPOINT\" is not defined!" && exit 0
+[ $? -ne 0 ] && echo "⚠ Error: Invalid MODE \"$MODE\"!" && exit 0
+[ -z "$RUNDIR" ] && echo "⚠ Error: Variable \"RUNDIR\" is not defined!" && exit 0
+[ -z "$ENTRYPOINT" ] && echo "⚠ Error: Variable \"ENTRYPOINT\" is not defined!" && exit 0
 CMD="$RUNDIR/$ENTRYPOINT"
-[ ! -f "$CMD" ] && echo "⚠ Entrypoint file \"$CMD\" not found!" && exit 0
+[ ! -f "$CMD" ] && echo "⚠ Error: Entrypoint file \"$CMD\" not found!" && exit 0
 ### shell command
 SHELLCMD="bash"
 # [ "$DEBUG" = "1" ] && SHELLCMD="bash -x"
@@ -36,25 +36,28 @@ cd $RUNDIR
 ### graphic mode ###
 if [ $GRAPHIC -eq 1 ] ; then
     xhost +                     # FIXME: try to be no so permissive!
+    [ -z "$DISPLAY" ] && echo "⚠ Error: DISPLAY variable is not set!" && exit 0
     # export VNCPORT=${DISPLAY:1} # remove ':' from $DISPLAY
 fi
 
 ### docker run ###
 if [ -n "$DOCKER" ] ; then
     trap 'dockerclean' EXIT
-    [ -z "$DOCKERTIMEOUT" ] && echo "⚠ Variable \"DOCKERTIMEOUT\" is not defined!" && exit 0
+    [ -z "$DOCKERTIMEOUT" ] && echo "⚠ Error: Variable \"DOCKERTIMEOUT\" is not defined!" && exit 0
     # check if docker image is already installed
     docker image inspect $DOCKER &> output
-    [ $? -ne 0 ] && echo "⚠ Docker image \"$DOCKER\" is required, but not locally installed!" && cat output && exit 0
+    [ $? -ne 0 ] && echo "⚠ Error: Docker image \"$DOCKER\" is required, but not locally installed!" && cat output && exit 0
     # DOCKEROPT="--privileged"
-    # DOCKEROPT="$DOCKEROPT -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix"
-    XDISPLAY=$(sed -e 's/.*:\(.*\)/\1/' <<< $DISPLAY)
-    XSOCK="/tmp/.X11-unix/X$XDISPLAY"
-    [ ! -S /tmp/.X11-unix/X$XDISPLAY ] && echo "⚠ X11 socket \"$XSOCK\" not found!" && exit 0
-    # [ $GRAPHIC -eq 1 ] && echo "DISPLAY=$DISPLAY"
-    # [ $GRAPHIC -eq 1 ] && echo "XSOCK=$XSOCK"
-    DOCKEROPT="$DOCKEROPT -e DISPLAY=$DISPLAY -v $XSOCK:$XSOCK"
-    # DOCKEROPT="$DOCKEROPT --device=/dev/dri:/dev/dri" # direct rendering
+    if [ $GRAPHIC -eq 1 ] ; then
+        # DOCKEROPT="$DOCKEROPT -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix"
+        XDISPLAY=$(sed -e 's/.*:\(.*\)/\1/' <<< $DISPLAY)
+        XSOCK="/tmp/.X11-unix/X$XDISPLAY"
+        [ ! -S /tmp/.X11-unix/X$XDISPLAY ] && echo "⚠ Error: X11 socket \"$XSOCK\" not found!" && exit 0
+        # [ $GRAPHIC -eq 1 ] && echo "DISPLAY=$DISPLAY"
+        # [ $GRAPHIC -eq 1 ] && echo "XSOCK=$XSOCK"
+        DOCKEROPT="$DOCKEROPT -e DISPLAY=$DISPLAY -v $XSOCK:$XSOCK"
+        # DOCKEROPT="$DOCKEROPT --device=/dev/dri:/dev/dri" # direct rendering
+    fi
     if [ -S /var/run/docker.sock ] ; then
         DOCKEROPT="$DOCKEROPT -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker"
     else
